### ISSUE TITLE
PostCSS plugin?

### ISSUE THREAD

**Issue by martinbavio** [css-modules/icss#11]
Is there any PostCSS plugin that implements this specification the same way webpack `css-loader` does? 

Problem is that when using other PostCSS that depends on imported constants, the order of loaders makes using this feature from css-loader not a possibility. So I was thinking if there was any PostCSS plugin that could help me with that, otherwise I would like to try to write one. Any guides in order to do it properly?

PS: I know [this](https://github.com/css-modules/postcss-modules-values) exists, but I do agree with [this](https://github.com/css-modules/css-modules-loader-core/pull/28#issuecomment-230344378) comment on that not being what I'm looking for.

**Comment by TrySound** [comment]
There's [postcss-icss](https://github.com/css-modules/postcss-icss) in dev process
