### ISSUE TITLE
Tweak to the BEM example

### ISSUE THREAD

**Issue by fvsch** [css-modules/icss#5]
In `README.md`:

> In BEM, that takes the form `.block-name__element-name--modifier-name`, or `.BlockName__elementName--modifierName`.

Looks like your second example is meant to illustrate the SUIT CSS flavor of BEM. If that is the case, it should be: `.BlockName-elementName--modifierName`.

**Comment by TrySound** [comment]
Nope. It's just illustrate camel case.
