### ISSUE TITLE
[rfc] Disallowing duplicate keys across :export blocks

### ISSUE THREAD

**Issue by DanielHeath** [css-modules/icss#6]
I'm writing to suggest a revision to the `icss` spec (If this has already been discussed, my apologies).

Currently, duplicate keys and multiple `:export` blocks are both valid `icss`, but I think the combination is awkward.

Consider the case where you edit a file with two `:export` blocks - one at the start and one at the end, not appearing on screen at the same time. If a key is duplicated between these blocks, changes made in the 'obvious' place (the first block) will appear to be silently swallowed.

I can see a few possible changes that reduce the impact of this:
- Disallow duplicate keys between blocks (I'd hope there are not many cases where this would break)
- Disallow duplicate keys at all (I can't think of a situation where duplicate keys are something other than an accident, but backwards compatibility makes this hard)
- Disallow multiple export blocks (backwards compatibility also makes this hard)

**Comment by TrySound** [comment]
It's stylistic recommendation, but the world is not ideal, so parsers will check everything. Duplicating keys will be processed before icss parsing. I mean plugins like scope or values should warn about overriding keys. This will be the most informative.

**Comment by DanielHeath** [comment]
Fair enough; `icss` isn't meant to be written by humans; I can have rules at a higher layer for this sort of thing.
