### ISSUE TITLE
RFC: Require imports to appear before they are used

### ISSUE THREAD

**Issue by DanielHeath** [css-modules/icss#9]
The current spec as written requires a backtracking parser, as it does not enforce that imports appear before they are used.

Writing a backtracking parser is significantly more work than writing a single-pass parser, and this makes implementing compatible tools harder.

I propose that the spec be amended to state that `:import` applies from that point in the file to the end of the file and does not modify anything earlier in the file.

**Comment by TrySound** [comment]
Simple string parser will be quite fast. Statements are simple to detect. Then will be replacement process by regular expression, which is still fast and simple. Doing traverse twice with postcss also not so significant in performance.

**Comment by DanielHeath** [comment]
Performance is not my argument. The point of `icss` as a low-level format is that different programs can be compatible with one another. 

The more things the spec allows, the more opportunities there are for misunderstandings.
